<?php
/**
 * One-time setup - creates config/database.php
 * Delete this file or rename after setup for security
 */
require_once __DIR__ . '/config/app.php';

$configFile = __DIR__ . '/config/database.php';
if (file_exists($configFile)) {
    header('Location: ' . APP_URL . '/');
    exit;
}

$error = '';
$success = false;

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    $host = trim($_POST['db_host'] ?? 'localhost');
    $name = trim($_POST['db_name'] ?? '');
    $user = trim($_POST['db_user'] ?? '');
    $pass = $_POST['db_pass'] ?? '';
    
    if (empty($name) || empty($user)) {
        $error = 'Database name and user are required.';
    } else {
        $content = "<?php\n/**\n * Database configuration - Auto-generated by setup\n */\n\n";
        $content .= "define('DB_HOST', " . var_export($host, true) . ");\n";
        $content .= "define('DB_NAME', " . var_export($name, true) . ");\n";
        $content .= "define('DB_USER', " . var_export($user, true) . ");\n";
        $content .= "define('DB_PASS', " . var_export($pass, true) . ");\n";
        $content .= "define('DB_CHARSET', 'utf8mb4');\n\n";
        $content .= "function getDB() {\n";
        $content .= "    static \$pdo = null;\n";
        $content .= "    if (\$pdo === null) {\n";
        $content .= "        try {\n";
        $content .= "            \$dsn = \"mysql:host=\" . DB_HOST . \";dbname=\" . DB_NAME . \";charset=\" . DB_CHARSET;\n";
        $content .= "            \$pdo = new PDO(\$dsn, DB_USER, DB_PASS, [\n";
        $content .= "                PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,\n";
        $content .= "                PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC,\n";
        $content .= "            ]);\n";
        $content .= "        } catch (PDOException \$e) {\n";
        $content .= "            die(\"Database connection failed: \" . \$e->getMessage());\n";
        $content .= "        }\n";
        $content .= "    }\n";
        $content .= "    return \$pdo;\n";
        $content .= "}\n";
        
        if (@file_put_contents($configFile, $content)) {
            // Test connection
            try {
                $dsn = "mysql:host=$host;dbname=$name;charset=utf8mb4";
                new PDO($dsn, $user, $pass, [PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION]);
                $success = true;
            } catch (PDOException $e) {
                $error = 'Connection failed: ' . $e->getMessage();
                @unlink($configFile);
            }
        } else {
            $error = 'Could not create config/database.php. Check folder permissions (config/ must be writable).';
        }
    }
}
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Setup - <?= APP_NAME ?></title>
    <link rel="stylesheet" href="<?= APP_URL ?>/assets/css/style.css">
</head>
<body class="auth-page">
    <div class="auth-card" style="max-width: 480px;">
        <div class="auth-header">
            <img src="<?= APP_URL ?>/assets/images/logo.png" alt="Webspace" style="height:64px; margin-bottom:0.75rem;">
            <h1>Database Setup</h1>
            <p>Enter your MySQL credentials to complete installation</p>
        </div>
        <?php if ($success): ?>
        <div class="alert alert-success">
            Database configured successfully! <a href="<?= APP_URL ?>/">Open site</a> · <a href="<?= APP_URL ?>/login">Log in</a>
        </div>
        <p class="text-muted" style="font-size:0.85rem; margin-top:1rem;">
            Run <code>database/schema.sql</code> in phpMyAdmin if you haven't created the tables yet.
        </p>
        <?php elseif ($error): ?>
        <div class="alert alert-error"><?= htmlspecialchars($error) ?></div>
        <?php endif; ?>
        <?php if (!$success): ?>
        <form method="POST" class="auth-form">
            <div class="form-group">
                <label for="db_host">Database Host</label>
                <input type="text" id="db_host" name="db_host" value="localhost" required>
            </div>
            <div class="form-group">
                <label for="db_name">Database Name</label>
                <input type="text" id="db_name" name="db_name" required placeholder="e.g. u232647434_Invoice">
            </div>
            <div class="form-group">
                <label for="db_user">Database User</label>
                <input type="text" id="db_user" name="db_user" required>
            </div>
            <div class="form-group">
                <label for="db_pass">Database Password</label>
                <input type="password" id="db_pass" name="db_pass">
            </div>
            <button type="submit" class="btn btn-primary btn-block">Create Config & Test</button>
        </form>
        <?php endif; ?>
    </div>
</body>
</html>
